logging:
  mode: online
  project: # Adapt
  notes: SIMCellViT
  log_comment: SIMCellViT_1600_skin_50-Fold-1
  tags:
  - "Fold-1"
  - "SIMCellViT_1600_skin_35unfreeze"
  wandb_dir: ./results
  log_dir: ./results/PanNuke/SIMCellViT_1600_skin_50
  level: Debug
  group: SIMCellViT_dlbcl_60

random_seed: 19

gpu: 0

run_sweep: False

data:
  dataset: PanNuke
  dataset_path: /data/pwojcik/SimMIM/pannuke
  train_folds:
  - 1
  - 3
  val_folds:
  - 2
  num_nuclei_classes: 6
  num_tissue_classes: 19

model:
  ema_decay: 0.996
  backbone: SimViT
  pretrained_encoder: /data/pwojcik/SimMIM/output_dir_sim1600_skin/checkpoint-49.pth # Adapt to your path
  shared_skip_connections: true

loss:
  nuclei_binary_map:
    focaltverskyloss:
      loss_fn: FocalTverskyLoss
      weight: 1
    dice:
      loss_fn: dice_loss
      weight: 1
  hv_map:
    mse:
      loss_fn: mse_loss_maps
      weight: 2.5
    msge:
      loss_fn: msge_loss_maps
      weight: 8
  nuclei_type_map:
    bce:
      loss_fn: xentropy_loss
      weight: 0.5
    dice:
      loss_fn: dice_loss
      weight: 0.2
    mcfocaltverskyloss:
      loss_fn: MCFocalTverskyLoss
      weight: 0.5
      args:
        num_classes: 6
  tissue_types:
    ce:
      loss_fn: CrossEntropyLoss
      weight: 0.1

training:
  drop_rate: 0
  mixed_precision: 0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  batch_size: 16
  epochs: 130
  optimizer: AdamW
  early_stopping_patience: 130
  scheduler:
    scheduler_type: exponential
    hyperparameters:
      gamma: 0.85
  optimizer_hyperparameter:
    betas:
    - 0.85
    - 0.95
    lr: 0.0003
    weight_decay: 0.0001
  unfreeze_epoch: 25
  sampling_gamma: 0.85
  sampling_strategy: cell+tissue
  unsupervised:
    flag_extra_weak: False
    threshold: -0.7   # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ params1: 0.7, 0.75, 0.8, 0.85, 0.9, 0.95
    loss_weight: 2.0

transformations:
  randomrotate90:
    p: 0.5
  horizontalflip:
    p: 0.5
  verticalflip:
    p: 0.5
  downscale:
    p: 0.15
    scale: 0.5
  blur:
    p: 0.2
    blur_limit: 10
  gaussnoise:
    p: 0.25
    var_limit: 50
  colorjitter:
    p: 0.2
    scale_setting: 0.25
    scale_color: 0.1
  superpixels:
    p: 0.1
  zoomblur:
    p: 0.1
  randomsizedcrop:
    p: 0.1
  elastictransform:
    p: 0.2
  normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5

eval_checkpoint: "latest_checkpoint.pth"
